import Head from "next/head";
import Sidebar from "../src/components/sidebar";
import Card from "../src/components/Card";
import Chart from "../src/components/Chart";
import styles from "../styles/Home.module.scss";
import useSWR, { useSWRConfig } from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const { data: profit } = useSWR("/api/profit", fetcher);
  const { data: statistikOmset } = useSWR("/api/statistik/omset", fetcher);
  const { data: statistikTransaksi } = useSWR(
    "/api/statistik/transaksi",
    fetcher
  );

  const currencyFormatter = (val) => {
    let formatter = new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      maximumFractionDigits: 0,
    });

    return formatter.format(val);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <Sidebar />

      <main>
        <h1 className={styles.header}>Dashboard</h1>
        <div className={"flex " + styles.statCards}>
          {profit && profit[0] && (
            <Card blue>
              <p>Total Keuntungan</p>
              <p className={styles.textHighlight}>
                {currencyFormatter(profit[0].sum)}
              </p>
            </Card>
          )}
          {statistikOmset && statistikTransaksi && (
            <>
              <Card blue>
                <p>Penjualan Hari ini</p>
                <p className={styles.textHighlight}>
                  {statistikOmset[0].penjualan_today ?? 0}
                </p>
                <p className={styles.subText}>
                  vs kemarin{" "}
                  {statistikOmset[0].persen_perubahan_omset_harian ?? 0}%
                </p>
              </Card>
              <Card blue>
                <p>Penjualan Hari ini</p>
                <p className={styles.textHighlight}>
                  {statistikTransaksi[0].penjualan_today ?? 0}
                </p>
                <p className={styles.subText}>
                  vs kemarin {statistikTransaksi[0].persen_perubahan_orderan}%
                </p>
              </Card>
            </>
          )}
        </div>

        <div className={styles.chart}>
          <Chart />
        </div>
      </main>
    </div>
  );
}
