import Head from "next/head";
import Sidebar from "../src/components/sidebar";
import Card from "../src/components/Card";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <Sidebar />

      <main>
        <h1 className={styles.header}>Dashboard</h1>
        <div className={"flex " + styles.statCards}>
          <Card blue>
            <p>Total Keuntungan</p>
            <p className={styles.textHighlight}>Rp. 120.000</p>
            <p className={styles.subText}>vs kemarin 12%</p>
          </Card>
          <Card blue>
            <p>Total Keuntungan</p>
            <p className={styles.textHighlight}>Rp. 120.000</p>
            <p className={styles.subText}>vs kemarin 12%</p>
          </Card>
          <Card>
            <p>Total Keuntungan</p>
            <p className={styles.textHighlight}>Rp. 120.000</p>
            <p className={styles.subText}>vs kemarin 12%</p>
          </Card>
        </div>
      </main>
    </div>
  );
}
